### ISSUE TITLE
Secret word

### ISSUE THREAD

**Issue by KrishnaPG** [craigchristenson/woocommerce-2checkout-api#1]
First of all - thank you for creating this plugin.

I am checking it out on a woocommerce site.

On the woocommerce-settings for this: there is no field named "secret word". Wondering where one should enter the secret word from the 2CO.

Also, settings has "public" and "private" keys - looked all over the 2CO tabs. No where such words could be found. Am I missing anything?

Thank you for your time on this.

**Comment by d1ch0t0my** [comment]
I wanted to ask the same question. Where does the secret word go? There is no field in WooCommerce's settings for it.

**Comment by jmcconnell91** [comment]
In a 2Checkout account, the secret word is used primarily for calculating the md5 hash for return validation.

Since the payment API system does not redirect off of the website, return validation is not necessary, so the secret word is not required.

**Comment by d1ch0t0my** [comment]
Thanks for the quick reply. I'm with you so in the 2Checkout Settings section your instructions that say "Enter your Secret Word (Must be the same value entered in your WooCommerce admin.)" only applies to the Paypal integration. Do I have that right?

**Comment by jmcconnell91** [comment]
Yup, that's right
