### ISSUE TITLE
Javascript Error in 2co.js

### ISSUE THREAD

**Issue by mrose15** [craigchristenson/woocommerce-2checkout-api#10]
Hello,
I'm having an issue with this plugin. I've installed version 0.0.2 and it's not revealing credit card fields and paypal is not being accepted as payment option. With the old version (0.0.1), the credit card fields are displayed by default but when a user selects paypal as an option and clicks "Place Order," the credit card form displays this error: "Credit Card details are incorrect, please try again."
Not sure if this is related but I noticed a javascript error in 2co.js (see screenshot below).
![2cojs_error](https://cloud.githubusercontent.com/assets/1874610/12305398/71253392-b9e9-11e5-9ec6-d53a2ea3be39.png)
Any assistance would be appreciated. 
Thank you,
Michele
michele@9seeds.com

**Comment by craigchristenson** [comment]
Thanks for reporting the issue. To try to replicate I did a fresh install of WP 4.4.1 and WooCommerce 2.4.13 and installed master, but could not replicate any issue. Both PayPal Direct and Credit Card payments are working properly for me. Looks like your screenshot shows this function getting called on an object that is not an array. Maybe we have a conflict with another plugin or theme you have installed. Please let me know what Wordpress and WooCommerce versions you are running so that we can figure out whats going on here and get it fixed. Thanks.

**Comment by mrose15** [comment]
Hi Craig,
I apologize for the long delay in my response. (Flu's not fun). My WP version is 4.4.1 and WC version is 2.5.0. Also, not sure if it matters, but I've taken a screen of all the WC add-ons the site is using.
<img width="1188" alt="screen shot 2016-01-22 at 4 35 44 pm" src="https://cloud.githubusercontent.com/assets/1874610/12526802/5ea319b6-c126-11e5-855a-05519cc95cd2.png">
- Michele

**Comment by craigchristenson** [comment]
Still having a hard time replicating on my end. Would it be ok if I place some test sales on your staging site to debug?

**Comment by mrose15** [comment]
Hi Craig,
Yes that's not a problem. Aside from a WP username and password, what other
site access do you need?
Login: http://buildloghomes.staging.wpengine.com/
Username: craigchristenson
password: 0NFe1EqJzWkWSlkonI7lfX)% (it should have been sent to you, but
just in case)

Let me know if there's anything else you need.
- Michele

**Comment by mrose15** [comment]
I've also been notified of this problem from our client:
I've noticed that every time someone pays with Paypal, our WooCommerce
times out. After a while we get an email from our Woo store that says an
order has been cancelled. When I open the order (for example:
https://www.buildloghomes.org/wp-admin/post.php?post=52255&action=edit) it
says:
"Unpaid order cancelled – time limit reached. Order status changed from
Pending Payment to Cancelled."
But the payment has gone through, and we get a notice from 2CO that a
payment has been received. So I manually change the order from cancelled to
processing to get the automatic FUE emails flowing.
Just FYI, dunno if they are related.

**Comment by mrose15** [comment]
Hi Craig,
Just following up on this. Any help would be greatly appreciated.
Thanks!
Michele

**Comment by craigchristenson** [comment]
The JS error is not affecting the request to 2Checkout. That is a legitimate failure to authorize response from 2Checkout. Can you please input this merchant's sandbox credentials and enable sandbox mode on this staging shop? I'll continue to troubleshoot with you.

**Comment by mrose15** [comment]
Hi Chris,
Which credentials are you looking for? If you're looking for WP
credentials, I sent them a few days ago.
Login: http://buildloghomes.staging.wpengine.com/
Username: craigchristenson
password: 0NFe1EqJzWkWSlkonI7lfX)% (it should have been sent to you, but
just in case)
How would I go about enabling sandbox mode?

Thanks

**Comment by craigchristenson** [comment]
You just need to setup a sandbox account at https://sandbox.2checkout.com . Then click the checkbox to enable sandbox mode in the wpecommerce 2checkout config on your staging site and input your sandbox credentials.

**Comment by mrose15** [comment]
Hi Craig, I appreciate your help on this for now but I believe that this js error might be unrelated to your plugin. We're also going to remove paypal from my client's site at this time as it's not a heavily used transaction method. Thanks again for your time.

**Comment by craigchristenson** [comment]
No worries. Let me know if you run into issues in the future.

**Comment by mrose15** [comment]
Hi Craig,
After further digging I found that the original js error I sent you was conflicting with the latest version of WooCommerce Follow Up Email add-on version 4.4.11. However, version 4.4.7 works just fine. I'm thinking this is because that add-on hardcoded a jquery file in there and it's an old version, but I'm not entirely sure. Let me know if this helps. Thanks!
