### ISSUE TITLE
Parameters not passing in Paypal 

### ISSUE THREAD

**Issue by limon213** [craigchristenson/woocommerce-2checkout-api#11]
When 2co redirect payment to paypal page order summary is not showing. check my screenshot http://postimg.org/image/9iqfjwv1p/ . How do I fix it? 

Thanks

**Comment by craigchristenson** [comment]
Hi limon123. This module passes the woocommerce cart identifier (merchant order id) to 2Checkout instead of the individual lineitem data so this data is not available when they reach PayPal. If you would like the lineitem data to be passed we may be able to add it as a feature in the future.
