### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by musiXboy** [craigchristenson/woocommerce-2checkout-api#15]
When I checkout at https://2ndsenseaudio.com/product/wiggle/, there is a warning said "Internal Server Error", what's wrong on my side?

Thanks a lot.

**Comment by craigchristenson** [comment]
Are you still experiencing an issue with your integration? I would like to help if you are.
Thanks,
Craig

**Comment by calebh05** [comment]
@musiXboy Are you still experiencing issues by chance? Let us know please so that we may advise further.

Thanks!
