### ISSUE TITLE
twocheckoutpp Issue after update woocommerce 

### ISSUE THREAD

**Issue by infopriyank** [craigchristenson/woocommerce-2checkout-api#16]
Hi Craig,

After update woocomerce in new version 2.6.1 paypal button not working . its only shows message Thank you for your order. We are now redirecting you to PayPal to make payment. but it is not redirecting on paypal please check this issue .

```
                                  Thanks in Advance
```

Regards
Priyank

**Comment by infopriyank** [comment]
Hi Craig,

Please give reply.

**Comment by craigchristenson** [comment]
I created a new install of WC 2.6.1 on top of WP 4.5.3 to test but cannot replicate any issue with PayPal direct. Can you please open up the JavaScript console in your browser and look for any errors? We could have a conflict with another plugin you are using.

**Comment by infopriyank** [comment]
Hi Craig,

Thanks for reply . i have checked JavaScript console but not found any error message and check all plugin also here is my store url  https://floradoor.staging.wpengine.com. please check once again .

Thanks
Priyank

**Comment by craigchristenson** [comment]
It looks like the jQuery block function is not being found for some reason. The blockUI js file is being pulled in as normal, but on your checkout page it arrears that the block() function that woocommerce uses to wrap blockUI() is not defined. I suppose that this could be theme related, does it work on the default theme in your install?
