### ISSUE TITLE
What should we set in 2checkout Webhooks INS URL?

### ISSUE THREAD

**Issue by piyushpune** [craigchristenson/woocommerce-2checkout-api#20]
http://yourdomain.com/?wc-api=WC_Gateway_Twocheckout  Thsi one?

So that order get completed automatically @craigchristenson @DennisAlund @jmcconnell91

**Comment by craigchristenson** [comment]
This plugin uses the response from the API to verify that an order has completed successfully. It does not include support for the 2Checkout's INS but we could add that feature in the future.
