### ISSUE TITLE
ISSUE - Double Payment

### ISSUE THREAD

**Issue by sditrapani** [craigchristenson/woocommerce-2checkout-api#21]
Thanks for creating this, it is much appreciated.

One problem that I have experienced is: 
> customer enters delivery info and credit card info
> all fields on delivery info and credit card info go blank (while it is loading the authorisation)
> customer enters their info again > double payment now happens

Is it possible to have a 'loading wheel' type effect happen whilst authorisation is happening to let the customer know that the process is busy.

**Comment by craigchristenson** [comment]
Yes woocommerce uses the blockui jquery plugin to handle this when the final submit button is clicked so that animation should be firing, I'll take a look. Please let me know what version you are using so that I can try to replicate the issue.

**Comment by sditrapani** [comment]
Thanks for quick reply. I'm using woocommerce version 4.7.2 and latest wp version.

Would minificaiton of CSS and JavaScript files be an issue? I am using WP Rocket and have minification and concatenation enabled.

**Comment by sditrapani** [comment]
PS - Update:

I turned off all minification and concatenation and 'problem' still exists.

**Comment by craigchristenson** [comment]
I just made a fresh install using the latest versions of woocommerce and wordpress using the default theme and the woocommerce's blockUI loading indicator is showing during the authorization process. If you want to take this offline I'll be happy to look at your site, just email the details.

**Comment by sditrapani** [comment]
Thanks, I've emailed you the details.

**Comment by craigchristenson** [comment]
Thanks but I never got an email from you. Please contact me at craigpchristenson@gmail.com with the details so I can look into this further.

**Comment by sditrapani** [comment]
I've sent the mail again, please let me know if you still don't receive it.
Thanks again!

**Comment by craigchristenson** [comment]
Thanks i got it. Looks like your theme bypasses the woocommerce default call to blockUI when the submit is clicked. I checked other payment methods and they also suffer from this. In this case I would alter the JS in your theme to use blockui [as it is used in the woocommerce default checkout.js](https://github.com/woocommerce/woocommerce/blob/173543ba82f4335184687af73f75671e2377a66e/assets/js/frontend/checkout.js). If you need help with the work around feel free to ping me by email with the theme that needs modified and we can work on it together.
