### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by newguy37** [craigchristenson/woocommerce-2checkout-api#22]
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin install failed.
![65bcb6ff7ae64aa188462910e83678a3](https://cloud.githubusercontent.com/assets/25437206/22432856/61419b5e-e6e4-11e6-8cfa-9eb675a04b8a.png)

**Comment by newguy37** [comment]
Unable to Upload the zip file unto Woocommerce WP

**Comment by craigchristenson** [comment]
You will need to extract the archive and copy the 'twocheckout' folder to your WordPress plugins directory under '/wp-content/plugins'. Then in your WordPress admin, you can navigate to Plugins and install the plugin. Please let me know if you have any more issues.
