### ISSUE TITLE
how to customize the input form? 

### ISSUE THREAD

**Issue by marcx00** [craigchristenson/woocommerce-2checkout-api#23]
I have a problem with the year select form, the down arrow is obscuring the year date.
I how could I customize it? 
Please find attached a screen shot of this issue.

Thanks advanced.
![input-f1](https://cloud.githubusercontent.com/assets/25484530/22513299/ca587416-e8d6-11e6-97af-d1c77eba8004.PNG)
![input-f2](https://cloud.githubusercontent.com/assets/25484530/22513300/ca6302dc-e8d6-11e6-9d95-02891e4cf6c3.PNG)

**Comment by craigchristenson** [comment]
Thank you for reporting this issue. The module uses the default woocommerce css class for the credit card form.
https://github.com/craigchristenson/woocommerce-2checkout-api/blob/master/twocheckout/wc-twocheckout.php#L251

You can change the class or add inline css directly on the select tag in the module as shown above.
