### ISSUE TITLE
Twocheckoutpp* Gateway Disabled: 2Checkout does not support your store currency.

### ISSUE THREAD

**Issue by marcx00** [craigchristenson/woocommerce-2checkout-api#24]
Hello,

Twocheckoutpp 2Checkout PayPal, Gateway Disabled: 2Checkout does not support your store currency.

My store currency is Hong Kong Dollar and your plugin is saying it does not support my store currency?
But 2CO do state that they support HKD?
http://help.2checkout.com/articles/Knowledge_Article/2Checkout-Offers-87-Currency-Options/?q=2Checkout+PayPal+currency&l=en_US&fs=Search&pn=1

**Comment by craigchristenson** [comment]
Sorry for the confusion. For PayPal transactions, 2Checkout only supports (USD, AUD, CAD, EUR, GBP). For credit card transactions, HKD would be supported.
