### ISSUE TITLE
Undefined property: WC_Gateway_Twocheckout::$debug

### ISSUE THREAD

**Issue by d1ch0t0my** [craigchristenson/woocommerce-2checkout-api#7]
Hi Craig,

I have 3 instances of the following error in admin area and one on the payment section of the front end:

WC_Gateway_Twocheckout::$debug in /home/mysite/beta2/wp-content/plugins/twocheckout/wc-twocheckout.php on line 47

Notice: Undefined property: WC_Gateway_Twocheckout::$debug in /home/mysite/beta2/wp-content/plugins/twocheckout/wc-twocheckout.php on line 47

Notice: Undefined property: WC_Gateway_Twocheckout::$debug in /home/mysite/beta2/wp-content/plugins/twocheckout/wc-twocheckout.php on line 47

Using this with WC 2.3.8 and WP 4.2.1. Have disabled all other plugins except WC and yours but no change. Any ideas on how to fix?

Thanks for any help.

**Comment by d1ch0t0my** [comment]
..so as a follow up to this apparently $woocommerce->logger has been removed from WC 2.3.5 onwards and plugins need to use the new WC_Logger class. I know you must be busy but an update to your very handy plugin would be appreciated to deal with this when you have time. Thanks mate.

**Comment by craigchristenson** [comment]
Thanks dude, I'll get a fix out shortly.

**Comment by jondcampbell** [comment]
Really looking forward to this fix as well.
thanks craig.

**Comment by craigchristenson** [comment]
Sorry for the delay, I was able to replicate on the latest woocommerce version and fix the issue. Please pull down master and let me know.

**Comment by jondcampbell** [comment]
I think that fixed it! Thanks.

**Comment by jondcampbell** [comment]
Hmm, maybe it didn't, still seeing errors at the checkout page.

**Comment by craigchristenson** [comment]
Hrmm.. Not able to replicate thus far. Can you add the errors your getting on the checkout page as well as your woocommerce version?

**Comment by craigchristenson** [comment]
@d1ch0t0my @jondcampbell are you still experiencing errors? Please let me know so I can help troubleshoot if you are.

**Comment by d1ch0t0my** [comment]
Hi Craig. Sorry to say I still see the following error in the backend WooCommerce > settings section:

WC_Gateway_Twocheckout::$debug in /home/mysite/public_html/wp-content/plugins/twocheckout/wc-twocheckout.php on line 51

..and the following error on all checkout pages:

Notice: Undefined property: WC_Gateway_Twocheckout::$debug in /home/mysite/public_html/wp-content/plugins/twocheckout/wc-twocheckout.php on line 51

This is on a clean install of WP 4.2.2 / WC 2.3.11 by the way.

**Comment by craigchristenson** [comment]
Thanks for the information, I was able to find and fix the cause. The notice should be resolved now in master.

**Comment by craigchristenson** [comment]
@d1ch0t0my,@jondcampbell
Were you able to test again against master? I was able to replicate the issues you reported on the latest woocommerce version and I was hoping to verify that the recent commits to master fixed your issues.

**Comment by jondcampbell** [comment]
Yes, the error is gone for me with the latest update.

**Comment by d1ch0t0my** [comment]
Sorry for delay in getting back Craig. Yes I can confirm you've nailed it. Thanks for your hard work.

**Comment by craigchristenson** [comment]
Glad to hear it, thanks.
