### ISSUE TITLE
Error : 2Checkout unsupported currency

### ISSUE THREAD

**Issue by technopluslk** [craigchristenson/woocommerce-2checkout-api#8]
Getting this error on Woocommerce checkout settings page.

"Gateway Disabled: 2Checkout does not support your store currency"

How to convert local currency to USD and pass the converted USD value to 2CO ?
Still need to keep the local currency as display currency in webstore.

**Comment by calebh05** [comment]
Hey @technopluslk - Any chance you're still having issues around currencies? If you are, please provide further details around the issue and which currency you're trying to process in.

Thanks!

**Comment by Dezueka** [comment]
Dear American,

I am in Laos and I have setting up the news of the main of the 2 checkoout but it said Gateway Disabled: 2Checkout does not support your store currency. Please help me fix it about this my store currency is LAK Lao Kips

**Comment by craigchristenson** [comment]
LAK is a supported currency in the credit card module (twocheckout) but it is not supported for the 2Checkout PayPal (twocheckoutpp) as it is not supported by 2Checkout when using the PayPal payment method.
