### ISSUE TITLE
unautherized error

### ISSUE THREAD

**Issue by Ranjani88** [craigchristenson/woocommerce-2checkout-api#9]
www.figureology.com this is my site . i am used woocomerce--2checkout-api . all details are given correctly. but it came "unauthorized" .whats the problem?. i have used 2checkout publisheable key and private key. used to test credit card details . please tell me solution .

**Comment by calebh05** [comment]
Hey @Ranjani88 - The unauthorized error occurs when a couple of things happen.

1. The live account credentials are being used while testing in sandbox or vice versa
2. An invalid token is present, or the token was already used on a prior call. 

If you're still experiencing this issue let us know.

Thanks!
